version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    command: bash -c "while ! pg_isready -h db -p 5433 -U $POSTGRES_USER; do sleep 1; done && sleep 5 && /app/init_db.sh"

