name: npmine_web_app
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - libffi=3.4.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.11.3
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - psycopg2
  - bs4
  - email_validator
  - pip:
      - alembic==1.11.1
      - bcrypt==4.0.1
      - blinker==1.6.2
      - bootstrap-flask==2.2.0
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - colorama==0.4.6
      - flask==2.3.2
      - flask-bcrypt==1.0.1
      - flask-login==0.6.2
      - flask-migrate==4.0.4
      - flask-sqlalchemy==3.0.3
      - flask-wtf==1.1.1
      - greenlet==2.0.2
      - idna==3.4
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - mako==1.2.4
      - markupsafe==2.1.3
      - requests==2.31.0
      - sqlalchemy==2.0.15
      - typing-extensions==4.6.3
      - urllib3==2.0.3
      - werkzeug==2.3.4
      - wtforms==3.0.1
