name: npmine_web_app
channels:
  - python3
dependencies:
  - pip=21.0.1=py37h06a4308_0
  - pip:
    click==8.1.2; python_version >= '3.7'
    flask-login==0.6.0
    flask-sqlalchemy==2.5.1
    flask==2.1.1
    greenlet==1.1.2; python_version >= '3' and platform_machine == 'aarch64' or (platform_machine == 'ppc64le' or (platform_machine == 'x86_64' or (platform_machine == 'amd64' or (platform_machine == 'AMD64' or (platform_machine == 'win32' or platform_machine == 'WIN32')))))
    importlib-metadata==4.11.3; python_version < '3.10'
    itsdangerous==2.1.2; python_version >= '3.7'
    jinja2==3.1.1; python_version >= '3.7'
    markupsafe==2.1.1; python_version >= '3.7'
    sqlalchemy==1.4.35; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4, 3.5'
    werkzeug==2.1.1; python_version >= '3.7'
    zipp==3.8.0; python_version >= '3.7'