name: npmine_web_app
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - boost=1.78.0
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bs4=4.12.2
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - cffi=1.15.1
  - colorama=0.4.6
  - contourpy=1.1.0
  - cryptography=39.0.0
  - cycler=0.11.0
  - decorator=5.1.1
  - dnspython=2.3.0
  - email-validator=1.3.1
  - email_validator=1.3.1
  - executing=1.2.0
  - expat=2.5.0
  - flask
  - flask-babel 
  - Flask-Script
  - flask-mail
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.40.0
  - freetype=2.12.1
  - freetype-py=2.3.0
  - gettext=0.21.1
  - greenlet=2.0.2
  - gunicorn
  - icu=72.1
  - idna=3.4
  - intel-openmp=2023.1.0
  - ipython=8.14.0
  - jedi=0.18.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libdeflate=1.18
  - libexpat=2.5.0
  - libffi=3.4.4
  - libglib=2.76.3
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libpng=1.6.39
  - libpq=15.1
  - libsqlite=3.41.2
  - libtiff=4.5.1
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libxml2=2.11.4
  - libzlib=1.2.13
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2022.1.0
  - munkres=1.1.4
  - numpy=1.25.0
  - openbabel=3.1.1
  - openjpeg=2.5.0
  - openssl=1.1.1u
  - packaging=23.1
  - pandas=2.0.3
  - parso=0.8.3
  - pcre2=10.40
  - pickleshare=0.7.5
  - pillow=10.0.0
  - pip=23.0.1
  - pixman=0.40.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psycopg2=2.9.3
  - pthread-stubs=0.4
  - pure_eval=0.2.2
  - pycairo=1.24.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.1.0
  - python=3.11
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - python-dotenv
  - pytz=2023.3
  - rdkit=2023.03.2
  - reportlab=4.0.4
  - rlpycairo=0.2.0
  - setuptools=67.8.0
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.9.0
  - tk=8.6.12
  - traitlets=5.9.0
  - typing_extensions=4.7.1
  - tzdata=2023c
  - wcwidth=0.2.6
  - wheel=0.38.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - alembic==1.11.1
      - bcrypt==4.0.1
      - blinker==1.6.2
      - bootstrap-flask==2.2.0
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - et-xmlfile==1.1.0
      - flask==2.3.2
      - flask-bcrypt==1.0.1
      - flask-login==0.6.2
      - flask-migrate==4.0.4
      - flask-sqlalchemy==3.0.3
      - flask-wtf==1.1.1
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - mako==1.2.4
      - markupsafe==2.1.3
      - openpyxl==3.1.2
      - pubchempy==1.0.4
      - python-dotenv==1.0.0
      - requests==2.31.0
      - sqlalchemy==2.0.15
      - tqdm==4.65.0
      - typing-extensions==4.6.3
      - urllib3==2.0.3
      - werkzeug==2.3.4
      - wtforms==3.0.1
