"""initial tables

Revision ID: 1b743ad9b749
Revises: 
Create Date: 2022-08-18 09:39:45.537783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b743ad9b749'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('doi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    op.create_table('compounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smiles', sa.String(length=150), nullable=True),
    sa.Column('inchi', sa.String(length=150), nullable=True),
    sa.Column('inchikey', sa.String(length=150), nullable=True),
    sa.Column('exactmolwt', sa.Integer(), nullable=True),
    sa.Column('pubchem', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inchi'),
    sa.UniqueConstraint('inchikey'),
    sa.UniqueConstraint('pubchem')
    )
    op.create_table('taxa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verbatim', sa.String(length=150), nullable=True),
    sa.Column('classificationPath', sa.String(length=150), nullable=True),
    sa.Column('classificationRank', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verbatim')
    )
    op.create_table('doicomp',
    sa.Column('doi_id', sa.Integer(), nullable=True),
    sa.Column('compounds_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compounds_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['doi_id'], ['doi.id'], )
    )
    op.create_table('doitaxa',
    sa.Column('doi_id', sa.Integer(), nullable=True),
    sa.Column('taxa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doi_id'], ['doi.id'], ),
    sa.ForeignKeyConstraint(['taxa_id'], ['taxa.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doitaxa')
    op.drop_table('doicomp')
    op.drop_table('taxa')
    op.drop_table('compounds')
    op.drop_table('doi')
    op.drop_table('accounts')
    # ### end Alembic commands ###
