"""added relationship tables

Revision ID: 2ac323abbe89
Revises: ce78d506d47b
Create Date: 2022-08-10 15:04:54.960386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac323abbe89'
down_revision = 'ce78d506d47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    op.create_table('doicomp',
    sa.Column('doi_id', sa.Integer(), nullable=True),
    sa.Column('compounds_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compounds_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['doi_id'], ['doi.id'], )
    )
    op.create_table('doitaxa',
    sa.Column('doi_id', sa.Integer(), nullable=True),
    sa.Column('taxa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doi_id'], ['doi.id'], ),
    sa.ForeignKeyConstraint(['taxa_id'], ['taxa.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doitaxa')
    op.drop_table('doicomp')
    op.drop_table('doi')
    # ### end Alembic commands ###
