"""changing to normal schema

Revision ID: b0be178b9965
Revises: 4088338e467e
Create Date: 2024-11-28 13:52:34.971306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0be178b9965'
down_revision = '4088338e467e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('changes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], name='audit_log_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='audit_log_pkey')
    )
    # ### end Alembic commands ###
