"""altering compound_images

Revision ID: b91baf33e923
Revises: 4ce0890619df
Create Date: 2024-11-26 11:54:36.538212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91baf33e923'
down_revision = '4ce0890619df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compounds', schema=None) as batch_op:
        batch_op.alter_column('compound_image',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compounds', schema=None) as batch_op:
        batch_op.alter_column('compound_image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)

    # ### end Alembic commands ###
