"""new tables

Revision ID: ce78d506d47b
Revises: c3248e5d1591
Create Date: 2022-08-10 14:40:56.980770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce78d506d47b'
down_revision = 'c3248e5d1591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smiles', sa.String(length=150), nullable=True),
    sa.Column('inchi', sa.String(length=150), nullable=True),
    sa.Column('inchikey', sa.String(length=150), nullable=True),
    sa.Column('exactmolwt', sa.Integer(), nullable=True),
    sa.Column('pubchem', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inchi'),
    sa.UniqueConstraint('inchikey'),
    sa.UniqueConstraint('pubchem')
    )
    op.create_table('taxa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verbatim', sa.String(length=150), nullable=True),
    sa.Column('classificationPath', sa.String(length=150), nullable=True),
    sa.Column('classificationRank', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verbatim')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxa')
    op.drop_table('compounds')
    # ### end Alembic commands ###
